_core:
  default_config_hash: HlN7eAN2N4JIHsYv56V4E7sqC9bS609KwvGFjyD_mgk
langcode: en
uuid: 28daa558-9e2c-4eea-a188-7ce5b0cc333c
name: Launchpad
mail: no-reply@thinkdrop.net
slogan: ''
page:
  403: ''
  404: ''
  front: /my
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: null
